### PR TITLE
Prune cities

### PR DESCRIPTION
**Pull request by logyball**
created a pruned cities list so that now we have the most populous city for each state, as well as the 50 most populous cities in the USA that aren't already on that list.  Also nixed Guam and Puerto Rico

### CODE REVIEW

**Comment by logyball** [comment]
also I think my instance of the 'prettier' code formatter is different from yours, it keeps re-adding () around one-param anonymous functions and adding commas to stuff...?

**Comment by rooneyshuman** [comment]
> also I think my instance of the 'prettier' code formatter is different from yours, it keeps re-adding () around one-param anonymous functions and adding commas to stuff...?

That's annoying. I've added the following to a config file for prettier to hopefully fix this issue:
image
Let me know if you notice any other differences in our formatting.

**Comment by rooneyshuman** [comment]
Looks good!

**Review by rooneyshuman — COMMENTED** [review]
LGTM!

**Pull request merged**
